//instead of create-react-app's approach where there's an index.html that has a div.root
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

//inter: font referenced by className
const inter = Inter({ subsets: ['latin'] })

//fills out the <head>
export const metadata: Metadata = {
  title: 'Comments Section | Review of \"Dragon 27\"',
  description: 'Generated by create next app',
}

type ChildrenObject = {
  children: React.ReactNode
};

//destructured object : TypeScript type declaration
export default function RootLayout({children,}: ChildrenObject) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
